name: flutter_markdown_selectionarea
description: A fork of flutter_markdown package with added support for SelectionArea.
repository: https://github.com/adrianjagielak/flutter_markdown_selectionarea
issue_tracker: https://github.com/adrianjagielak/flutter_markdown_selectionarea/issues
version: 0.6.17+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  markdown: ^7.0.0
  meta: ^1.3.0
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.1
  standard_message_codec: ^0.0.1+3
